production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  server_name: <%= ENV["SERVER_NAME"] %>
  force_ssl: true
  delay_jobs: false

mailer_delivery_method: :smtp
smtp_settings:
  :address: 'smtp.sendgrid.net'
  :port: 587
  :domain: <%= ENV["SERVER_NAME"] %>
  :user_name: <%= ENV["SENDGRID_USERNAME"] %>
  :password: <%= ENV["SENDGRID_PASSWORD"] %>
  :authentication: 'plain'
  :enable_starttls_auto: true
