local:
  service: TenantDisk
  root: <%= Rails.root.join("storage") %>

test:
  service: TenantDisk
  root: <%= Rails.root.join("tmp/storage") %>

s3:
  service: S3
  access_key_id: <%= ENV["BUCKETEER_AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["BUCKETEER_AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["BUCKETEER_AWS_REGION"] %>
  bucket: <%= ENV["BUCKETEER_BUCKET_NAME"] %>
# Remember not to checkin your GCS keyfile to a repository
# gcs:
#   service: GCS
#   project: <%= Rails.application.secrets.dig(:gcs, :project) %>
#   credentials: <%= Rails.root.join(Rails.application.secrets.dig(:gcs, :credentials).to_s) %>
#   bucket: <%= Rails.application.secrets.dig(:gcs, :bucket) %>

# azure:
#   service: AzureStorage
#   storage_account_name: <%= Rails.application.secrets.dig(:azure, :storage_account_name) %>
#   storage_access_key: <%= Rails.application.secrets.dig(:azure, :storage_access_key) %>
#   container: <%= Rails.application.secrets.dig(:azure, :container) %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ s3, gcs, azure ]
